spring.application.name=MovieApp
server.port=${PORT:8080}

# Gemini API
gemini.api.key=${GEMINI_API_KEY}
gemini.model=gemini-2.5-flash

# TMDB API
tmdb.api.url=https://api.themoviedb.org/3
tmdb.api.key=${TMDB_API_KEY}