spring.application.name=MovieApp
server.port=${PORT:8080}

# Gemini API
gemini.api.key=AIzaSyAISBpUMJnRtkycCcYGxK_fYZgqH6WBCZg
gemini.model=gemini-2.5-flash

# TMDB API
tmdb.api.url=https://api.themoviedb.org/3
tmdb.api.key=1fafae59993ade172f4f9c9a05d4196e